export const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Discipline equals freedom. - Jocko Willink",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work. - Stephen King",
  "Focus on being productive instead of busy. - Tim Ferriss",
  "Small daily improvements over time lead to stunning results. - Robin Sharma",
  "It is not death that a man should fear, but he should fear never beginning to live. - Marcus Aurelius",
  "We suffer more often in imagination than in reality. - Seneca",
  "He who has a why to live for can bear almost any how. - Friedrich Nietzsche",
  "The impediment to action advances action. What stands in the way becomes the way. - Marcus Aurelius",
  "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "In the middle of every difficulty lies opportunity. - Albert Einstein",
  "The best way to predict the future is to create it. - Peter Drucker",
  "I think, therefore I am. - René Descartes",
  "Happiness depends upon ourselves. - Aristotle",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "Don't cry because it's over, smile because it happened. - Dr. Seuss",
  "Be the change that you wish to see in the world. - Mahatma Gandhi",
  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
  "A person who never made a mistake never tried anything new. - Albert Einstein",
  "Everything you've ever wanted is on the other side of fear. - George Addair",
  "Fall seven times and stand up eight. - Japanese Proverb",
  "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
  "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "It is never too late to be what you might have been. - George Eliot",
  "You must be the change you wish to see in the world. - Mahatma Gandhi",
  "The best revenge is massive success. - Frank Sinatra",
  "If you judge people, you have no time to love them. - Mother Teresa",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "To love and be loved is to feel the sun from both sides. - David Viscott",
  "Love is a serious mental disease. - Plato",
  "We are shaped and fashioned by what we love. - Johann Wolfgang von Goethe",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours.' - Leah Busque",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "Opportunities don't happen. You create them. - Chris Grosser",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell",
  "If you want to achieve greatness stop asking for permission. - Anonymous",
  "Things work out best for those who make the best of how things work out. - John Wooden",
  "To live a creative life, we must lose our fear of being wrong. - Joseph Chilton Pearce",
  "If you are not willing to risk the usual you will have to settle for the ordinary. - Jim Rohn",
  "Trust because you are willing to accept the risk, not because it's safe or certain. - Anonymous",
  "Take up one idea. Make that one idea your life--think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
  "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
  "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
  "If you do what you always did, you will get what you always got. - Anonymous",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly. - Proverb",
  "Successful entrepreneurs are givers and not takers of positive energy. - Anonymous",
  "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. - Vaibhav Shah",
  "Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "If you don't value your time, neither will others. Stop giving away your time and talents--start charging for it. - Kim Garst",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
  "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
  "If you're going through hell keep going. - Winston Churchill",
  "The ones who are crazy enough to think they can change the world, are the ones that do. - Anonymous",
  "Don't raise your voice, improve your argument. - Anonymous",
  "What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
  "The meaning of life is to find your gift. The purpose of life is to give it away. - Anonymous",
  "The distance between insanity and genius is measured only by success. - Bruce Feirstein",
  "When you stop chasing the wrong things, you catch the right things. - Lolly Daskal",
  "I believe that the only courage anybody ever needs is the courage to follow your own dreams. - Oprah Winfrey",
  "No masterpiece was ever created by a lazy artist. - Anonymous",
  "Happiness is a butterfly, which when pursued, is always just beyond your grasp, but which, if you will sit down quietly, may alight upon you. - Nathaniel Hawthorne",
  "If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
  "Blessed are those who can give without remembering and take without forgetting. - Anonymous",
  "Do one thing every day that scares you. - Anonymous",
  "What's the point of being alive if you don't at least try to do something remarkable. - Anonymous",
  "Life is not about finding yourself. Life is about creating yourself. - Lolly Daskal",
  "Nothing in the world is more common than unsuccessful people with talent. - Anonymous",
  "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. - Anonymous",
  "Your problem isn't the problem. Your reaction is the problem. - Anonymous",
  "You can do anything, but not everything. - Anonymous",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
  "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. - A.P.J. Abdul Kalam",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "The starting point of all achievement is desire. - Napoleon Hill",
  "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
  "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson",
  "All progress takes place outside the comfort zone. - Michael John Bobak",
  "You may only succeed if you desire succeeding; you may only fail if you do not mind failing. - Philippos",
  "Courage is resistance to fear, mastery of fear--not absence of fear. - Mark Twain",
  "Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
  "People often say that motivation doesn't last. Well, neither does bathing--that's why we recommend it daily. - Zig Ziglar",
  "We become what we think about most of the time, and that's the strangest secret. - Earl Nightingale",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon"
]
